import type { Metadata } from "next";
import type { ReactNode, CSSProperties } from "react";
import { Bebas_Neue, Lora } from "next/font/google";
import "./globals.css";

const headings = Bebas_Neue({ subsets: ["latin"], variable: "--font-headings" });
const body = Lora({ subsets: ["latin"], variable: "--font-body" });

export const metadata: Metadata = {
  title: "Generated Site",
  description: "Auto-generated by The Brain v2",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${headings.variable} ${body.variable}`}
        style={{
          "--primary": "#1e1b4b",
          "--secondary": "#6366f1",
          "--accent": "#a5b4fc",
          "--bg": "#eef2ff",
          "--muted": "#818cf8",
        } as CSSProperties}
      >
        {children}
      </body>
    </html>
  );
}
