import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Brain v2 — Generated Site",
  description: "Auto-generated by The Brain v2",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={ inter.className } style={{ backgroundColor: "#1e293b" }}>
        {children}
      </body>
    </html>
  );
}
