import type { Metadata } from "next";
import type { ReactNode, CSSProperties } from "react";
import { Lora, Source_Sans_3 } from "next/font/google";
import "./globals.css";

const headings = Lora({ subsets: ["latin"], variable: "--font-headings" });
const body = Source_Sans_3({ subsets: ["latin"], variable: "--font-body" });

export const metadata: Metadata = {
  title: "Generated Site",
  description: "Auto-generated by The Brain v2",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${headings.variable} ${body.variable}`}
        style={{
          "--primary": "#292524",
          "--secondary": "#78716c",
          "--accent": "#d6d3d1",
          "--bg": "#fafaf9",
          "--muted": "#a8a29e",
        } as CSSProperties}
      >
        {children}
      </body>
    </html>
  );
}
